baseURL = "http://example.org/"
languageCode = "en-us"
summaryLength = 20
disqusShortname = ""
googleAnalytics = ""
Paginate = 10
PaginatePath = "/"
enableRobotsTXT = true

[taxonomies]
  category = "categories"

[markup.goldmark.renderer]
  unsafe = true # Allows HTML <img> tags inside Markdown content

[permalinks]
  posts = ":section/:year/:month/:day/:title/"

[params]
  backgroundImagePath = "/uploads/building.jpg"
  description = "Hugo template with example content for a law firm."
  images = ["siteicon.png"]
  title = "Justice Template"
